#! /bin/rdmd
/**
 * Generate flagdata.d.
 */

import std;


string dir = "../flags";
string pattern = "*.png";
string output = "../src/flagdata.d";
string header =
"/// Autogenerated by " ~ __FILE__  ~ " on " ~ __TIMESTAMP__ ~ ".

module flagdata;

__gshared ubyte[][string] flagFiles;

void initFlagFiles()
{
    flagFiles = [
";


void main()
{
    auto names = dirEntries(dir, pattern, SpanMode.shallow)
                 .map!(x => x.baseName)
                 .array;

    auto f = File(output, "w");
    f.write(header);

    enum fmt = "                 \"%s\": cast(ubyte[])import(\"%s\"),";
    foreach (n; names) {
        f.writefln!fmt(stripExtension(n), n);
    }

    f.writefln("                ];  // %s files\n}", names.length);

    writefln("Successfully created %s.", output);
}
