version: 1.0e.{branch}.{build}
image: Visual Studio 2022
environment:
  BASEDIR: C:\projects
install:
  - cd %BASEDIR%
  - cd
  - curl -sS -o dmd.7z https://downloads.dlang.org/releases/2.x/2.107.1/dmd.2.107.1.windows.7z
  - curl -sSL -o deps.zip https://github.com/user-attachments/files/27318971/monsterbrowser_deps-10b.zip
  - 7z x dmd.7z > NUL
  - unzip -q deps.zip
  - >
    for %%f in (qstat.exe libcurl32.dll libcurl64.dll maxminddb32.dll
    maxminddb64.dll GeoLite2-Country.mmdb) do copy %%f monster-browser\
  - cd monster-browser
  - path %BASEDIR%\dmd2\windows\bin;%PATH%
build_script: |
  dub build --build=release --config=windows --arch=x86
  make-package.bat
  cd misc
  "C:\Program Files (x86)\Inno Setup 6\iscc" /Q mb.iss
test: off
artifacts:
- path: MonsterBrowser.exe
- path: MonsterBrowser10e.zip
- path: misc\Monster Browser 1.0e Setup.exe
