version: 0.9d-{branch}.{build}
environment:
  BASEDIR: C:\projects
install: |
  cd %BASEDIR%
  cd
  curl -sS -o dmd.zip http://downloads.dlang.org/releases/2010/dmd.1.066.zip
  curl -sSL -o deps.zip https://github.com/torhus/monster-browser/files/9331932/monsterbrowser_deps.zip
  unzip -q dmd.zip
  unzip -q deps.zip
  copy sc.ini dmd\windows\bin\
  for %%f in (xfbuild.exe qstat.exe libmaxminddb.dll GeoLite2-Country.mmdb) do copy %%f monster-browser\
  xcopy /E /Q dwt-win monster-browser\
  cd monster-browser
  path %BASEDIR%\dmd\windows\bin;%PATH%
build_script: |
  build.bat release
  make-package.bat
  cd misc
  "C:\Program Files (x86)\Inno Setup 5\iscc" /Q mb.iss
test: off
artifacts:
- path: MonsterBrowser.exe
- path: MonsterBrowser09d.zip
- path: misc\Monster Browser 0.9d Setup.exe
