version: 0.9e.{branch}.{build}
image: Visual Studio 2022
environment:
  BASEDIR: C:\projects
install: |
  cd %BASEDIR%
  cd
  curl -sS -o dmd.7z https://downloads.dlang.org/releases/2.x/2.098.1/dmd.2.098.1.windows.7z
  curl -sSL -o deps.zip https://github.com/torhus/monster-browser/files/9473908/monsterbrowser_deps.zip
  7z x dmd.7z > NUL
  unzip -q deps.zip
  for %%f in (qstat.exe libmaxminddb.dll GeoLite2-Country.mmdb) do copy %%f monster-browser\
  cd monster-browser
  path %BASEDIR%\dmd2\windows\bin;%PATH%
build_script: |
  dub build --build=release --config=windows --arch=x86
  make-package.bat
  cd misc
  "C:\Program Files (x86)\Inno Setup 6\iscc" /Q mb.iss
test: off
artifacts:
- path: MonsterBrowser.exe
- path: MonsterBrowser09e.zip
- path: misc\Monster Browser 0.9e Setup.exe
