; Monster Browser game configuration

; Each [section] represents a game or mod.
; Lines beginning with a ";" are comments.
; More information: https://sites.google.com/site/monsterbrowser/#h.p_ID_75


[Quake III (all servers)]
alias=q3
gameTypes=FFA 1v1 SP TDM CTF
regkey=HKEY_LOCAL_MACHINE\SOFTWARE\Id\Quake III Arena\INSTALLEXEPATH
exename=quake3.exe

[baseq3]
inherit=q3
mod=baseq3

[OSP]
inherit=q3
mod=osp
gameTypes=FFA 1v1 SP TDM CTF CA

[CPMA]
inherit=q3
mod=cpma
gameTypes=FFA 1v1 DA TDM CTF CA FTAG CTFS 2v2

[Excessive Plus]
inherit=q3
mod=excessiveplus
gameTypes=FFA 1on1 SP TDM CTF RTF 1FCTF CA FTAG PTL

[DeFRaG]
inherit=q3
mod=defrag

[Q3Plus]
inherit=q3
mod=q3plus
gameTypes=FFA 1on1 SP TDM CTF RTF 1FCTF CA FTAG PTL

[Rocket Arena 3]
inherit=q3
mod=arena

[----------------]

[Urban Terror 4.3]
mod=q3ut4
masterServer=master.urbanterror.info:27900
gameTypes=FFA LMS 2 TDM TS FTL C&H CTF Bomb Jump FT Gun

[OpenArena]
masterServer=dpmaster.deathmask.net:27950
protocolVersion=71
gameTypes=FFA 1v1 SP TDM CTF OFC Ovl Harv Elim CTFE LMS DD Dom Pos

[Tremulous]
regKey=HKEY_LOCAL_MACHINE\SOFTWARE\Tremulous\InstallDir
exeName=tremulous.exe
masterServer=master.tremulous.net:30710
protocolVersion=69

[Smokin' Guns]
mod=smokinguns
regKey=HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Smokin' Guns Productions\Smokin' Guns\InstallPath
exeName=smokinguns.exe
masterServer=master.smokin-guns.org
gameTypes=FFA Duel 2 TDM RTP BR
etColors=true

[World of Padman]
mod=WorldofPadman
regKey=HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Padworld Entertainment\World of Padman 1.6.2\Path
exeName=wop.x86_64.exe
masterServer=master.worldofpadman.com:27955
protocolVersion=71
gameTypes=FFA 1v1 2 SyC LPS TDM CtL SyCT BB
qstatMasterServerType=worldofpadmanm
qstatConfigFile=qstat_mb.cfg
