#! /bin/rdmd
/**
 * Generate flagdata.d.
 */

import tango.io.FileScan;
import tango.io.Stdout;
import tango.io.Stream.TextFileStream;


const char[] DIR = "flags";
const char[] SUFFIX = ".png";
const char[] OUTPUT = "flagdata.d";

const char[] HEADER =
"/// Autogenerated by " __FILE__ " on " __TIMESTAMP__ ".

module flagdata;

ubyte[][char[]] flagFiles;

void initFlagFiles()
{
	flagFiles = [
";


int main()
{
	auto scan = new FileScan;

	scan(DIR, SUFFIX);
	Stdout.formatln("Found {} files in '{}'.", scan.files.length, DIR);
	if (scan.files.length < 100) {
		Stdout("ERROR: Suspiciously low number of files, aborting.");
		return 1;
	}

	auto f = new TextFileOutput(OUTPUT);
	scope (exit) f.flush.close;

	f.write(HEADER);
	foreach (i, path; scan.files) {
		f.format("\t             \"{}\": cast(ubyte[])import(\"{}\")",
		                                                      path.name, path);
		if (i < scan.files.length - 1)
			f.write(",");
		f.newline;
	}
	f.formatln("\t            ];  // {} files\n}", scan.files.length);

	Stdout.formatln("Successfully created {}.", OUTPUT);

	return 0;
}
